import "~/styles/globals.css";

import { Poppins as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: "300"
});
export const metadata = {
  title: "richmond college info site",
  description: "Generated by create-t3-app; coded by lazydukk",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${fontSans.variable}`}>{children}</body>
    </html>
  );
}
